// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCO6GAPh6iv02hZIt7k-P-XrgmQEhw180',
    appId: '1:720477611155:web:0ee8a7bdf215537b005966',
    messagingSenderId: '720477611155',
    projectId: 'task-8cd6a',
    authDomain: 'task-8cd6a.firebaseapp.com',
    storageBucket: 'task-8cd6a.appspot.com',
    measurementId: 'G-C6Q6PFDX49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLO_Iv1TNwS1C71ya9dQfi3iWG1SqHB98',
    appId: '1:720477611155:android:183fc4b6509bc04b005966',
    messagingSenderId: '720477611155',
    projectId: 'task-8cd6a',
    storageBucket: 'task-8cd6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjOQ-Gksyb5YOuEKwtyKNGPeROJHdLqbU',
    appId: '1:720477611155:ios:edcaade2bd803b0f005966',
    messagingSenderId: '720477611155',
    projectId: 'task-8cd6a',
    storageBucket: 'task-8cd6a.appspot.com',
    iosBundleId: 'com.example.task2Admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjOQ-Gksyb5YOuEKwtyKNGPeROJHdLqbU',
    appId: '1:720477611155:ios:edcaade2bd803b0f005966',
    messagingSenderId: '720477611155',
    projectId: 'task-8cd6a',
    storageBucket: 'task-8cd6a.appspot.com',
    iosBundleId: 'com.example.task2Admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCO6GAPh6iv02hZIt7k-P-XrgmQEhw180',
    appId: '1:720477611155:web:e197b4f8cd707666005966',
    messagingSenderId: '720477611155',
    projectId: 'task-8cd6a',
    authDomain: 'task-8cd6a.firebaseapp.com',
    storageBucket: 'task-8cd6a.appspot.com',
    measurementId: 'G-VFYXCBK7LE',
  );
}
